[package]
name = "derive-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
bincode = { version = "1.3.3"} 
serde = { version = "1.0.193", features = ["derive"] }
