[package]
name = "cybernet"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { version = "1.3.3"} 
clap = { version = "4.4.12", features = ["derive"] }
serde = { version = "1.0.193", features = ["derive"] }
derive-macro = { path = "./src/derive-macro"}
